name: Release

on:
  push:
    tags: ["v*"]
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o pg-archiver-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o pg-archiver-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o pg-archiver-darwin-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pg-archiver-linux-amd64
            pg-archiver-darwin-amd64
            pg-archiver-darwin-arm64
